import { type ThemePalette } from "./index";

export const ayuTheme: ThemePalette = {
    label: "Ayu",
    light: {
        bgPrimary: "#fcfcfc",
        bgSecondary: "#f8f9fa",
        bgTertiary: "#eef0f2",
        bgElevated: "#ffffff",
        textPrimary: "#5c6166",
        textSecondary: "#828e9f",
        textHeading: "#5c6166",
        textHeadingMuted: "#828e9f",
        border: "#e8eaed",
        accent: "#f29718",
        iconMuted: "#828e9f",
        shadowSoft: "0 18px 48px rgba(92, 97, 102, 0.08)",
        codeAnchors: {
            comment: "#adaeb1",
            constant: "#a37acc",
            escape: "#4cbf99",
            function: "#eba400",
            keyword: "#fa8532",
            markup: "#86b300",
            parameter: "#a37acc",
            property: "#f07171",
            string: "#86b300",
            type: "#22a4e6",
            typeParameter: "#55b4d4",
            variable: "#5c6166",
        },
    },
    dark: {
        bgPrimary: "#10141c",
        bgSecondary: "#0d1017",
        bgTertiary: "#151a23",
        bgElevated: "#141821",
        textPrimary: "#bfbdb6",
        textSecondary: "#8a97ad",
        textHeading: "#bfbdb6",
        textHeadingMuted: "#8a97ad",
        border: "#1b1f29",
        accent: "#e6b450",
        iconMuted: "#8a97ad",
        shadowSoft: "0 24px 56px rgba(0, 0, 0, 0.35)",
        codeAnchors: {
            comment: "#5a6673",
            constant: "#d2a6ff",
            escape: "#95e6cb",
            function: "#ffb454",
            keyword: "#ff8f40",
            markup: "#aad94c",
            parameter: "#d2a6ff",
            property: "#f07178",
            string: "#aad94c",
            type: "#59c2ff",
            typeParameter: "#59c2ff",
            variable: "#bfbdb6",
        },
    },
};
