import { type ThemePalette } from "./index";

export const catppuccinTheme: ThemePalette = {
    label: "Catppuccin",
    light: {
        bgPrimary: "#eff1f5",
        bgSecondary: "#e6e9ef",
        bgTertiary: "#dce0e8",
        bgElevated: "#f2f4f8",
        textPrimary: "#4c4f69",
        textSecondary: "#6c6f85",
        textHeading: "#4c4f69",
        textHeadingMuted: "#6c6f85",
        border: "#ccd0da",
        accent: "#8839ef",
        iconMuted: "#6c6f85",
        shadowSoft: "0 18px 48px rgba(76, 79, 105, 0.08)",
        codeAnchors: {
            comment: "#7c7f93",
            constant: "#fe640b",
            escape: "#ea76cb",
            function: "#1e66f5",
            keyword: "#8839ef",
            markup: "#1e66f5",
            parameter: "#e64553",
            property: "#179299",
            string: "#40a02b",
            type: "#df8e1d",
            typeParameter: "#04a5e5",
            variable: "#4c4f69",
        },
    },
    dark: {
        bgPrimary: "#1e1e2e",
        bgSecondary: "#262637",
        bgTertiary: "#313244",
        bgElevated: "#232336",
        textPrimary: "#cdd6f4",
        textSecondary: "#a6adc8",
        textHeading: "#cdd6f4",
        textHeadingMuted: "#a6adc8",
        border: "#45475a",
        accent: "#cba6f7",
        iconMuted: "#9399b2",
        shadowSoft: "0 24px 56px rgba(0, 0, 0, 0.35)",
        codeAnchors: {
            comment: "#9399b2",
            constant: "#fab387",
            escape: "#f5c2e7",
            function: "#89b4fa",
            keyword: "#cba6f7",
            markup: "#89b4fa",
            parameter: "#eba0ac",
            property: "#94e2d5",
            string: "#a6e3a1",
            type: "#f9e2af",
            typeParameter: "#89dceb",
            variable: "#cdd6f4",
        },
    },
};
