import { type ThemePalette } from "./index";

export const claudeTheme: ThemePalette = {
    label: "Claude",
    light: {
        bgPrimary: "#faf9f5",
        bgSecondary: "#f4f3ee",
        bgTertiary: "#e8e6dc",
        bgElevated: "#fdfcfa",
        textPrimary: "#141413",
        textSecondary: "#8a8780",
        textHeading: "color-mix(in srgb, var(--accent) 8%, var(--text-primary))",
        textHeadingMuted: "#8a8780",
        border: "#dfdcd4",
        accent: "#c15f3c",
        iconMuted: "#8a8780",
        shadowSoft: "0 18px 48px rgba(20, 20, 19, 0.07)",
        codeAnchors: {
            comment: "#8a8780",
            constant: "#9a3412",
            escape: "#be185d",
            function: "#c2410c",
            keyword: "#991b1b",
            markup: "#7c2d12",
            parameter: "#b45309",
            property: "#be123c",
            string: "#166534",
            type: "#854d0e",
            typeParameter: "#0e7490",
            variable: "#141413",
        },
    },
    dark: {
        bgPrimary: "#1a1917",
        bgSecondary: "#23221f",
        bgTertiary: "#2d2c28",
        bgElevated: "#1f1e1b",
        textPrimary: "#f4f3ee",
        textSecondary: "#a09d95",
        textHeading: "color-mix(in srgb, var(--accent) 12%, var(--text-primary))",
        textHeadingMuted: "#a09d95",
        border: "#3a3835",
        accent: "#d97757",
        iconMuted: "#908d86",
        shadowSoft: "0 24px 56px rgba(0, 0, 0, 0.32)",
        codeAnchors: {
            comment: "#a09d95",
            constant: "#f97316",
            escape: "#ec4899",
            function: "#fb923c",
            keyword: "#fca5a5",
            markup: "#fcd34d",
            parameter: "#fed7aa",
            property: "#fbcfe8",
            string: "#bef264",
            type: "#facc15",
            typeParameter: "#67e8f9",
            variable: "#f4f3ee",
        },
    },
};
