import { type ThemePalette } from "./index";

export const codexTheme: ThemePalette = {
    label: "Codex",
    light: {
        bgPrimary: "#ffffff",
        bgSecondary: "#f7f7f8",
        bgTertiary: "#ececf1",
        bgElevated: "#fcfcfd",
        textPrimary: "#1a1a1a",
        textSecondary: "#6e6e80",
        textHeading: "#1a1a1a",
        textHeadingMuted: "#6e6e80",
        border: "#e5e5ea",
        accent: "#10a37f",
        iconMuted: "#6e6e80",
        shadowSoft: "0 18px 48px rgba(0, 0, 0, 0.06)",
        codeAnchors: {
            comment: "#6e6e80",
            constant: "#9a3412",
            escape: "#be185d",
            function: "#047857",
            keyword: "#065f46",
            markup: "#166534",
            parameter: "#15803d",
            property: "#0e7490",
            string: "#854d0e",
            type: "#0f766e",
            typeParameter: "#1d4ed8",
            variable: "#1a1a1a",
        },
    },
    dark: {
        bgPrimary: "#1e1e20",
        bgSecondary: "#2a2a2d",
        bgTertiary: "#343537",
        bgElevated: "#252528",
        textPrimary: "#ececf1",
        textSecondary: "#8e8ea0",
        textHeading: "#ececf1",
        textHeadingMuted: "#8e8ea0",
        border: "#3c3c41",
        accent: "#10a37f",
        iconMuted: "#8e8ea0",
        shadowSoft: "0 24px 56px rgba(0, 0, 0, 0.35)",
        codeAnchors: {
            comment: "#8e8ea0",
            constant: "#fba17e",
            escape: "#f472b6",
            function: "#6ee7b7",
            keyword: "#86efac",
            markup: "#a7f3d0",
            parameter: "#bbf7d0",
            property: "#67e8f9",
            string: "#fde68a",
            type: "#5eead4",
            typeParameter: "#93c5fd",
            variable: "#ececf1",
        },
    },
};
