import { type ThemePalette } from "./index";

export const lavenderTheme: ThemePalette = {
    label: "Lavender",
    light: {
        bgPrimary: "#fcfaff",
        bgSecondary: "#f3eefb",
        bgTertiary: "#e8e0f5",
        bgElevated: "#fdfbff",
        textPrimary: "#1a1525",
        textSecondary: "#7c6f96",
        textHeading: "#1a1525",
        textHeadingMuted: "#7c6f96",
        border: "#ddd4ec",
        accent: "#8b5cf6",
        iconMuted: "#7c6f96",
        shadowSoft: "0 18px 48px rgba(26, 21, 37, 0.07)",
        codeAnchors: {
            comment: "#7c6f96",
            constant: "#9a3412",
            escape: "#be185d",
            function: "#6d28d9",
            keyword: "#5b21b6",
            markup: "#7e22ce",
            parameter: "#7c2d12",
            property: "#5b21b6",
            string: "#047857",
            type: "#854d0e",
            typeParameter: "#0e7490",
            variable: "#1a1525",
        },
    },
    dark: {
        bgPrimary: "#18141f",
        bgSecondary: "#211c2a",
        bgTertiary: "#2b2536",
        bgElevated: "#1c1825",
        textPrimary: "#e8e2f0",
        textSecondary: "#9b90ad",
        textHeading: "#e8e2f0",
        textHeadingMuted: "#9b90ad",
        border: "#352e42",
        accent: "#a78bfa",
        iconMuted: "#8d82a3",
        shadowSoft: "0 24px 56px rgba(0, 0, 0, 0.32)",
        codeAnchors: {
            comment: "#9b90ad",
            constant: "#fca5a5",
            escape: "#f472b6",
            function: "#c4b5fd",
            keyword: "#a78bfa",
            markup: "#ddd6fe",
            parameter: "#fde68a",
            property: "#f9a8d4",
            string: "#a7f3d0",
            type: "#fcd34d",
            typeParameter: "#67e8f9",
            variable: "#e8e2f0",
        },
    },
};
