import { type ThemePalette } from "./index";

export const nordTheme: ThemePalette = {
    label: "Nord",
    light: {
        bgPrimary: "#eceff4",
        bgSecondary: "#e5e9f0",
        bgTertiary: "#d8dee9",
        bgElevated: "#edf0f5",
        textPrimary: "#2e3440",
        textSecondary: "#4c566a",
        textHeading: "#2e3440",
        textHeadingMuted: "#4c566a",
        border: "#d0d6e1",
        accent: "#5e81ac",
        iconMuted: "#4c566a",
        shadowSoft: "0 18px 48px rgba(46, 52, 64, 0.08)",
        codeAnchors: {
            comment: "#4c566a",
            constant: "#b48ead",
            escape: "#d08770",
            function: "#5e81ac",
            keyword: "#5e81ac",
            markup: "#5e81ac",
            parameter: "#2e3440",
            property: "#2e3440",
            string: "#587539",
            type: "#5e81ac",
            typeParameter: "#5e81ac",
            variable: "#2e3440",
        },
    },
    dark: {
        bgPrimary: "#2e3440",
        bgSecondary: "#3b4252",
        bgTertiary: "#434c5e",
        bgElevated: "#333a47",
        textPrimary: "#eceff4",
        textSecondary: "#d8dee9",
        textHeading: "#eceff4",
        textHeadingMuted: "#d8dee9",
        border: "#4c566a",
        accent: "#88c0d0",
        iconMuted: "#b0b8c8",
        shadowSoft: "0 24px 56px rgba(0, 0, 0, 0.30)",
        codeAnchors: {
            comment: "#616e88",
            constant: "#b48ead",
            escape: "#ebcb8b",
            function: "#88c0d0",
            keyword: "#81a1c1",
            markup: "#88c0d0",
            parameter: "#d8dee9",
            property: "#d8dee9",
            string: "#a3be8c",
            type: "#8fbcbb",
            typeParameter: "#8fbcbb",
            variable: "#d8dee9",
        },
    },
};
