import { type ThemePalette } from "./index";

export const sunsetTheme: ThemePalette = {
    label: "Sunset",
    light: {
        bgPrimary: "#fefaf8",
        bgSecondary: "#f8efe8",
        bgTertiary: "#f0e2d6",
        bgElevated: "#fffbf9",
        textPrimary: "#21150e",
        textSecondary: "#8c6e5a",
        textHeading: "color-mix(in srgb, var(--accent) 8%, var(--text-primary))",
        textHeadingMuted: "#8c6e5a",
        border: "#e6d4c4",
        accent: "#ea580c",
        iconMuted: "#8c6e5a",
        shadowSoft: "0 18px 48px rgba(33, 21, 14, 0.07)",
        codeAnchors: {
            comment: "#8c6e5a",
            constant: "#b45309",
            escape: "#be123c",
            function: "#c2410c",
            keyword: "#7c2d12",
            markup: "#9f1239",
            parameter: "#78350f",
            property: "#854d0e",
            string: "#166534",
            type: "#4a044e",
            typeParameter: "#1e40af",
            variable: "#21150e",
        },
    },
    dark: {
        bgPrimary: "#1a1410",
        bgSecondary: "#251d17",
        bgTertiary: "#30261e",
        bgElevated: "#1f1914",
        textPrimary: "#ece2d8",
        textSecondary: "#a8917e",
        textHeading: "color-mix(in srgb, var(--accent) 12%, var(--text-primary))",
        textHeadingMuted: "#a8917e",
        border: "#3c3028",
        accent: "#fb923c",
        iconMuted: "#9e8774",
        shadowSoft: "0 24px 56px rgba(0, 0, 0, 0.32)",
        codeAnchors: {
            comment: "#a8917e",
            constant: "#fcd34d",
            escape: "#f472b6",
            function: "#fdba74",
            keyword: "#fb923c",
            markup: "#fca5a5",
            parameter: "#fed7aa",
            property: "#fbcfe8",
            string: "#bef264",
            type: "#facc15",
            typeParameter: "#67e8f9",
            variable: "#ece2d8",
        },
    },
};
