import { type ThemePalette } from "./index";

export const synthwave84Theme: ThemePalette = {
    label: "Synthwave '84",
    light: {
        bgPrimary: "#faf5ff",
        bgSecondary: "#f0eaf8",
        bgTertiary: "#e4dcf0",
        bgElevated: "#fdf9ff",
        textPrimary: "#2a2139",
        textSecondary: "#695d85",
        textHeading: "color-mix(in srgb, var(--accent) 10%, var(--text-primary))",
        textHeadingMuted: "#695d85",
        border: "#dbd2ec",
        accent: "#d946a8",
        iconMuted: "#695d85",
        shadowSoft: "0 18px 48px rgba(42, 33, 57, 0.10)",
        codeAnchors: {
            comment: "#5a5f8a",
            constant: "#a02e22",
            escape: "#0a6b6a",
            function: "#0a6b6a",
            keyword: "#7a5c00",
            markup: "#1a7a52",
            parameter: "#9b1f7a",
            property: "#9b1f7a",
            string: "#8a3a00",
            type: "#a00e1a",
            typeParameter: "#a00e1a",
            variable: "#9b1f7a",
        },
    },
    dark: {
        bgPrimary: "#262335",
        bgSecondary: "#241b2f",
        bgTertiary: "#2a2139",
        bgElevated: "#1e1a2c",
        textPrimary: "#ffffff",
        textSecondary: "#848bbd",
        textHeading: "color-mix(in srgb, var(--accent) 14%, var(--text-primary))",
        textHeadingMuted: "#848bbd",
        border: "#34294f",
        accent: "#ff7edb",
        iconMuted: "#7a73a6",
        shadowSoft: "0 24px 56px rgba(0, 0, 0, 0.40)",
        codeAnchors: {
            comment: "#848bbd",
            constant: "#f97e72",
            escape: "#36f9f6",
            function: "#36f9f6",
            keyword: "#fede5d",
            markup: "#72f1b8",
            parameter: "#ff7edb",
            property: "#ff7edb",
            string: "#ff8b39",
            type: "#fe4450",
            typeParameter: "#fe4450",
            variable: "#ff7edb",
        },
    },
};
