import type { ThemeName } from "./index";

export interface AnsiPalette {
    black: string;
    red: string;
    green: string;
    yellow: string;
    blue: string;
    magenta: string;
    cyan: string;
    white: string;
    brightBlack: string;
    brightRed: string;
    brightGreen: string;
    brightYellow: string;
    brightBlue: string;
    brightMagenta: string;
    brightCyan: string;
    brightWhite: string;
}

type TerminalPaletteByMode = {
    dark: AnsiPalette;
    light: AnsiPalette;
};

// Maps a theme + isDark flag to an intentionally-designed 16-colour ANSI
// palette. Keep this exhaustive so new app themes cannot accidentally reuse
// stale terminal colors from the previously-applied theme.
const PALETTES: Record<ThemeName, TerminalPaletteByMode> = {
    catppuccin: {
        dark: {
            // Catppuccin Mocha
            black:         "#45475a",
            red:           "#f38ba8",
            green:         "#a6e3a1",
            yellow:        "#f9e2af",
            blue:          "#89b4fa",
            magenta:       "#cba6f7",
            cyan:          "#94e2d5",
            white:         "#bac2de",
            brightBlack:   "#585b70",
            brightRed:     "#f38ba8",
            brightGreen:   "#a6e3a1",
            brightYellow:  "#f9e2af",
            brightBlue:    "#89b4fa",
            brightMagenta: "#cba6f7",
            brightCyan:    "#89dceb",
            brightWhite:   "#a6adc8",
        },
        light: {
            // Catppuccin Latte
            black:         "#9ca0b0",
            red:           "#d20f39",
            green:         "#40a02b",
            yellow:        "#df8e1d",
            blue:          "#1e66f5",
            magenta:       "#8839ef",
            cyan:          "#179299",
            white:         "#5c5f77",
            brightBlack:   "#acb0be",
            brightRed:     "#d20f39",
            brightGreen:   "#40a02b",
            brightYellow:  "#df8e1d",
            brightBlue:    "#1e66f5",
            brightMagenta: "#8839ef",
            brightCyan:    "#179299",
            brightWhite:   "#4c4f69",
        },
    },
    nord: {
        dark: {
            black:         "#3b4252",
            red:           "#bf616a",
            green:         "#a3be8c",
            yellow:        "#ebcb8b",
            blue:          "#81a1c1",
            magenta:       "#b48ead",
            cyan:          "#88c0d0",
            white:         "#e5e9f0",
            brightBlack:   "#4c566a",
            brightRed:     "#bf616a",
            brightGreen:   "#a3be8c",
            brightYellow:  "#ebcb8b",
            brightBlue:    "#81a1c1",
            brightMagenta: "#b48ead",
            brightCyan:    "#8fbcbb",
            brightWhite:   "#eceff4",
        },
        light: {
            black:         "#3b4252",
            red:           "#bf616a",
            green:         "#a3be8c",
            yellow:        "#ebcb8b",
            blue:          "#5e81ac",
            magenta:       "#b48ead",
            cyan:          "#88c0d0",
            white:         "#434c5e",
            brightBlack:   "#4c566a",
            brightRed:     "#bf616a",
            brightGreen:   "#a3be8c",
            brightYellow:  "#ebcb8b",
            brightBlue:    "#81a1c1",
            brightMagenta: "#b48ead",
            brightCyan:    "#8fbcbb",
            brightWhite:   "#2e3440",
        },
    },
    solarized: {
        dark: {
            black:         "#073642",
            red:           "#dc322f",
            green:         "#859900",
            yellow:        "#b58900",
            blue:          "#268bd2",
            magenta:       "#d33682",
            cyan:          "#2aa198",
            white:         "#eee8d5",
            brightBlack:   "#002b36",
            brightRed:     "#cb4b16",
            brightGreen:   "#586e75",
            brightYellow:  "#657b83",
            brightBlue:    "#839496",
            brightMagenta: "#6c71c4",
            brightCyan:    "#93a1a1",
            brightWhite:   "#fdf6e3",
        },
        light: {
            black:         "#eee8d5",
            red:           "#dc322f",
            green:         "#859900",
            yellow:        "#b58900",
            blue:          "#268bd2",
            magenta:       "#d33682",
            cyan:          "#2aa198",
            white:         "#073642",
            brightBlack:   "#fdf6e3",
            brightRed:     "#cb4b16",
            brightGreen:   "#93a1a1",
            brightYellow:  "#839496",
            brightBlue:    "#657b83",
            brightMagenta: "#6c71c4",
            brightCyan:    "#586e75",
            brightWhite:   "#002b36",
        },
    },
    tokyoNight: {
        dark: {
            black:         "#15161e",
            red:           "#f7768e",
            green:         "#9ece6a",
            yellow:        "#e0af68",
            blue:          "#7aa2f7",
            magenta:       "#bb9af7",
            cyan:          "#7dcfff",
            white:         "#a9b1d6",
            brightBlack:   "#414868",
            brightRed:     "#f7768e",
            brightGreen:   "#9ece6a",
            brightYellow:  "#e0af68",
            brightBlue:    "#7aa2f7",
            brightMagenta: "#bb9af7",
            brightCyan:    "#7dcfff",
            brightWhite:   "#c0caf5",
        },
        light: {
            black:         "#e9e9ec",
            red:           "#8c4351",
            green:         "#485e30",
            yellow:        "#8f5e15",
            blue:          "#2959aa",
            magenta:       "#5a4a78",
            cyan:          "#0f4b6e",
            white:         "#6172b0",
            brightBlack:   "#a8aecb",
            brightRed:     "#8c4351",
            brightGreen:   "#485e30",
            brightYellow:  "#8f5e15",
            brightBlue:    "#2959aa",
            brightMagenta: "#5a4a78",
            brightCyan:    "#0f4b6e",
            brightWhite:   "#343b58",
        },
    },
    gruvbox: {
        dark: {
            black:         "#282828",
            red:           "#cc241d",
            green:         "#98971a",
            yellow:        "#d79921",
            blue:          "#458588",
            magenta:       "#b16286",
            cyan:          "#689d6a",
            white:         "#a89984",
            brightBlack:   "#928374",
            brightRed:     "#fb4934",
            brightGreen:   "#b8bb26",
            brightYellow:  "#fabd2f",
            brightBlue:    "#83a598",
            brightMagenta: "#d3869b",
            brightCyan:    "#8ec07c",
            brightWhite:   "#ebdbb2",
        },
        light: {
            black:         "#fbf1c7",
            red:           "#9d0006",
            green:         "#79740e",
            yellow:        "#b57614",
            blue:          "#076678",
            magenta:       "#8f3f71",
            cyan:          "#427b58",
            white:         "#7c6f64",
            brightBlack:   "#928374",
            brightRed:     "#cc241d",
            brightGreen:   "#98971a",
            brightYellow:  "#d79921",
            brightBlue:    "#458588",
            brightMagenta: "#b16286",
            brightCyan:    "#689d6a",
            brightWhite:   "#3c3836",
        },
    },
    rosePine: {
        dark: {
            black:         "#26233a",
            red:           "#eb6f92",
            green:         "#31748f",
            yellow:        "#f6c177",
            blue:          "#9ccfd8",
            magenta:       "#c4a7e7",
            cyan:          "#ebbcba",
            white:         "#e0def4",
            brightBlack:   "#403d52",
            brightRed:     "#eb6f92",
            brightGreen:   "#31748f",
            brightYellow:  "#f6c177",
            brightBlue:    "#9ccfd8",
            brightMagenta: "#c4a7e7",
            brightCyan:    "#ebbcba",
            brightWhite:   "#e0def4",
        },
        light: {
            black:         "#f2e9e1",
            red:           "#b4637a",
            green:         "#286983",
            yellow:        "#ea9d34",
            blue:          "#56949f",
            magenta:       "#907aa9",
            cyan:          "#d7827e",
            white:         "#575279",
            brightBlack:   "#9893a5",
            brightRed:     "#b4637a",
            brightGreen:   "#286983",
            brightYellow:  "#ea9d34",
            brightBlue:    "#56949f",
            brightMagenta: "#907aa9",
            brightCyan:    "#d7827e",
            brightWhite:   "#575279",
        },
    },
    kanagawa: {
        dark: {
            black:         "#16161d",
            red:           "#c34043",
            green:         "#76946a",
            yellow:        "#c0a36e",
            blue:          "#7e9cd8",
            magenta:       "#957fb8",
            cyan:          "#6a9589",
            white:         "#c8c093",
            brightBlack:   "#717c7c",
            brightRed:     "#ff5d62",
            brightGreen:   "#98bb6c",
            brightYellow:  "#e6c384",
            brightBlue:    "#7fb4ca",
            brightMagenta: "#938aa9",
            brightCyan:    "#7aa89f",
            brightWhite:   "#dcd7ba",
        },
        light: {
            black:         "#f2ecbc",
            red:           "#c84053",
            green:         "#6f894e",
            yellow:        "#77713f",
            blue:          "#4d699b",
            magenta:       "#624c83",
            cyan:          "#4e8ca2",
            white:         "#545464",
            brightBlack:   "#8a8980",
            brightRed:     "#c84053",
            brightGreen:   "#6f894e",
            brightYellow:  "#836f4a",
            brightBlue:    "#4d699b",
            brightMagenta: "#624c83",
            brightCyan:    "#4e8ca2",
            brightWhite:   "#43436c",
        },
    },
    everforest: {
        dark: {
            black:         "#374247",
            red:           "#e67e80",
            green:         "#a7c080",
            yellow:        "#dbbc7f",
            blue:          "#7fbbb3",
            magenta:       "#d699b6",
            cyan:          "#83c092",
            white:         "#d3c6aa",
            brightBlack:   "#475258",
            brightRed:     "#e67e80",
            brightGreen:   "#a7c080",
            brightYellow:  "#dbbc7f",
            brightBlue:    "#7fbbb3",
            brightMagenta: "#d699b6",
            brightCyan:    "#83c092",
            brightWhite:   "#d3c6aa",
        },
        light: {
            black:         "#f3ead3",
            red:           "#f85552",
            green:         "#8da101",
            yellow:        "#dfa000",
            blue:          "#3a94c5",
            magenta:       "#df69ba",
            cyan:          "#35a77c",
            white:         "#5c6a72",
            brightBlack:   "#a6b0a0",
            brightRed:     "#f85552",
            brightGreen:   "#8da101",
            brightYellow:  "#dfa000",
            brightBlue:    "#3a94c5",
            brightMagenta: "#df69ba",
            brightCyan:    "#35a77c",
            brightWhite:   "#272d30",
        },
    },
    ayu: {
        dark: {
            black:         "#0a0e14",
            red:           "#ff3333",
            green:         "#b8cc52",
            yellow:        "#e7c547",
            blue:          "#36a3d9",
            magenta:       "#f07178",
            cyan:          "#95e6cb",
            white:         "#c7c7c7",
            brightBlack:   "#686868",
            brightRed:     "#f07178",
            brightGreen:   "#cae682",
            brightYellow:  "#ffd580",
            brightBlue:    "#73d0ff",
            brightMagenta: "#f07178",
            brightCyan:    "#95e6cb",
            brightWhite:   "#ffffff",
        },
        light: {
            black:         "#f0f0f0",
            red:           "#e65050",
            green:         "#48a223",
            yellow:        "#f28b28",
            blue:          "#399ee6",
            magenta:       "#a37acc",
            cyan:          "#4cbf99",
            white:         "#575f66",
            brightBlack:   "#8a9199",
            brightRed:     "#e65050",
            brightGreen:   "#86b300",
            brightYellow:  "#f28b28",
            brightBlue:    "#399ee6",
            brightMagenta: "#a37acc",
            brightCyan:    "#4cbf99",
            brightWhite:   "#1a1f29",
        },
    },
    nightOwl: {
        dark: {
            black:         "#011627",
            red:           "#ef5350",
            green:         "#22da6e",
            yellow:        "#addb67",
            blue:          "#82aaff",
            magenta:       "#c792ea",
            cyan:          "#21c7a8",
            white:         "#d6deeb",
            brightBlack:   "#575656",
            brightRed:     "#ef5350",
            brightGreen:   "#22da6e",
            brightYellow:  "#ffeb95",
            brightBlue:    "#82aaff",
            brightMagenta: "#c792ea",
            brightCyan:    "#7fdbca",
            brightWhite:   "#ffffff",
        },
        light: {
            black:         "#f0f0f0",
            red:           "#de3d3b",
            green:         "#08916a",
            yellow:        "#e0a000",
            blue:          "#2d79c7",
            magenta:       "#7c4dff",
            cyan:          "#008997",
            white:         "#403f53",
            brightBlack:   "#989fb1",
            brightRed:     "#de3d3b",
            brightGreen:   "#08916a",
            brightYellow:  "#daaa01",
            brightBlue:    "#2d79c7",
            brightMagenta: "#7c4dff",
            brightCyan:    "#008997",
            brightWhite:   "#090a0f",
        },
    },
    vesper: {
        dark: {
            black:         "#101010",
            red:           "#f04e4e",
            green:         "#5ab875",
            yellow:        "#f5a623",
            blue:          "#5f9cff",
            magenta:       "#cf7bdb",
            cyan:          "#2ebcb3",
            white:         "#cccccc",
            brightBlack:   "#555555",
            brightRed:     "#ff7171",
            brightGreen:   "#7dd496",
            brightYellow:  "#ffc966",
            brightBlue:    "#82b4ff",
            brightMagenta: "#e39fe8",
            brightCyan:    "#4fd4cc",
            brightWhite:   "#eeeeee",
        },
        light: {
            black:         "#f4f4f4",
            red:           "#c0392b",
            green:         "#27ae60",
            yellow:        "#d68910",
            blue:          "#2471a3",
            magenta:       "#8e44ad",
            cyan:          "#148f77",
            white:         "#555555",
            brightBlack:   "#999999",
            brightRed:     "#e74c3c",
            brightGreen:   "#2ecc71",
            brightYellow:  "#f39c12",
            brightBlue:    "#3498db",
            brightMagenta: "#9b59b6",
            brightCyan:    "#1abc9c",
            brightWhite:   "#222222",
        },
    },
    synthwave84: {
        dark: {
            black:         "#191a28",
            red:           "#fe4450",
            green:         "#72f1b8",
            yellow:        "#fede5d",
            blue:          "#36f9f6",
            magenta:       "#e2a0ff",
            cyan:          "#72f1b8",
            white:         "#f9f9f9",
            brightBlack:   "#495495",
            brightRed:     "#f97e72",
            brightGreen:   "#72f1b8",
            brightYellow:  "#fede5d",
            brightBlue:    "#36f9f6",
            brightMagenta: "#e2a0ff",
            brightCyan:    "#36f9f6",
            brightWhite:   "#fefefe",
        },
        light: {
            // Synthwave is inherently dark — use a softened version for light
            black:         "#f0eeff",
            red:           "#c0003c",
            green:         "#006b3e",
            yellow:        "#8a6500",
            blue:          "#0060a0",
            magenta:       "#7c00b8",
            cyan:          "#006b6b",
            white:         "#2d2357",
            brightBlack:   "#8080b0",
            brightRed:     "#fe4450",
            brightGreen:   "#00a860",
            brightYellow:  "#c0a000",
            brightBlue:    "#2060c8",
            brightMagenta: "#b060d8",
            brightCyan:    "#00a0a0",
            brightWhite:   "#191a28",
        },
    },
    // ── App-specific themes ───────────────────────────────────────────────────
    default: {
        dark: {
            black:         "#252525",
            red:           "#f87171",
            green:         "#4ade80",
            yellow:        "#fbbf24",
            blue:          "#818cf8",
            magenta:       "#c084fc",
            cyan:          "#34d399",
            white:         "#d4d4d4",
            brightBlack:   "#525252",
            brightRed:     "#fca5a5",
            brightGreen:   "#86efac",
            brightYellow:  "#fde68a",
            brightBlue:    "#a5b4fc",
            brightMagenta: "#d8b4fe",
            brightCyan:    "#6ee7b7",
            brightWhite:   "#e8e8e8",
        },
        light: {
            black:         "#f5f5f5",
            red:           "#dc2626",
            green:         "#16a34a",
            yellow:        "#d97706",
            blue:          "#4f46e5",
            magenta:       "#7c3aed",
            cyan:          "#059669",
            white:         "#404040",
            brightBlack:   "#a3a3a3",
            brightRed:     "#ef4444",
            brightGreen:   "#22c55e",
            brightYellow:  "#f59e0b",
            brightBlue:    "#6366f1",
            brightMagenta: "#8b5cf6",
            brightCyan:    "#10b981",
            brightWhite:   "#1c1c1c",
        },
    },
    ocean: {
        dark: {
            black:         "#1e293b",
            red:           "#f87171",
            green:         "#34d399",
            yellow:        "#fbbf24",
            blue:          "#38bdf8",
            magenta:       "#818cf8",
            cyan:          "#22d3ee",
            white:         "#cbd5e1",
            brightBlack:   "#475569",
            brightRed:     "#fca5a5",
            brightGreen:   "#6ee7b7",
            brightYellow:  "#fde68a",
            brightBlue:    "#7dd3fc",
            brightMagenta: "#a5b4fc",
            brightCyan:    "#67e8f9",
            brightWhite:   "#e2e8f0",
        },
        light: {
            black:         "#e2e8f0",
            red:           "#be123c",
            green:         "#047857",
            yellow:        "#b45309",
            blue:          "#0284c7",
            magenta:       "#4338ca",
            cyan:          "#0e7490",
            white:         "#334155",
            brightBlack:   "#94a3b8",
            brightRed:     "#dc2626",
            brightGreen:   "#059669",
            brightYellow:  "#d97706",
            brightBlue:    "#0ea5e9",
            brightMagenta: "#4f46e5",
            brightCyan:    "#0891b2",
            brightWhite:   "#0f172a",
        },
    },
    forest: {
        dark: {
            black:         "#1a2820",
            red:           "#f87171",
            green:         "#34d399",
            yellow:        "#fbbf24",
            blue:          "#60a5fa",
            magenta:       "#a78bfa",
            cyan:          "#2dd4bf",
            white:         "#d1fae5",
            brightBlack:   "#374c3d",
            brightRed:     "#fca5a5",
            brightGreen:   "#6ee7b7",
            brightYellow:  "#fde68a",
            brightBlue:    "#93c5fd",
            brightMagenta: "#c4b5fd",
            brightCyan:    "#5eead4",
            brightWhite:   "#ecfdf5",
        },
        light: {
            black:         "#f0fdf4",
            red:           "#b91c1c",
            green:         "#047857",
            yellow:        "#92400e",
            blue:          "#1d4ed8",
            magenta:       "#6d28d9",
            cyan:          "#0f766e",
            white:         "#14532d",
            brightBlack:   "#86efac",
            brightRed:     "#ef4444",
            brightGreen:   "#10b981",
            brightYellow:  "#d97706",
            brightBlue:    "#3b82f6",
            brightMagenta: "#7c3aed",
            brightCyan:    "#14b8a6",
            brightWhite:   "#052e16",
        },
    },
    rose: {
        dark: {
            black:         "#1a1215",
            red:           "#fb7185",
            green:         "#4ade80",
            yellow:        "#fbbf24",
            blue:          "#60a5fa",
            magenta:       "#e879f9",
            cyan:          "#34d399",
            white:         "#fce7f3",
            brightBlack:   "#4c1d3a",
            brightRed:     "#fda4af",
            brightGreen:   "#86efac",
            brightYellow:  "#fde68a",
            brightBlue:    "#93c5fd",
            brightMagenta: "#f0abfc",
            brightCyan:    "#6ee7b7",
            brightWhite:   "#fff1f2",
        },
        light: {
            black:         "#fff1f2",
            red:           "#be123c",
            green:         "#047857",
            yellow:        "#b45309",
            blue:          "#1d4ed8",
            magenta:       "#a21caf",
            cyan:          "#0f766e",
            white:         "#9f1239",
            brightBlack:   "#fda4af",
            brightRed:     "#f43f5e",
            brightGreen:   "#10b981",
            brightYellow:  "#f59e0b",
            brightBlue:    "#3b82f6",
            brightMagenta: "#d946ef",
            brightCyan:    "#14b8a6",
            brightWhite:   "#500724",
        },
    },
    amber: {
        dark: {
            black:         "#1a1710",
            red:           "#f87171",
            green:         "#4ade80",
            yellow:        "#f59e0b",
            blue:          "#60a5fa",
            magenta:       "#e879f9",
            cyan:          "#34d399",
            white:         "#fef3c7",
            brightBlack:   "#44390a",
            brightRed:     "#fca5a5",
            brightGreen:   "#86efac",
            brightYellow:  "#fde68a",
            brightBlue:    "#93c5fd",
            brightMagenta: "#f0abfc",
            brightCyan:    "#6ee7b7",
            brightWhite:   "#fffbeb",
        },
        light: {
            black:         "#fffbeb",
            red:           "#b91c1c",
            green:         "#047857",
            yellow:        "#b45309",
            blue:          "#1d4ed8",
            magenta:       "#7c3aed",
            cyan:          "#0f766e",
            white:         "#78350f",
            brightBlack:   "#fde68a",
            brightRed:     "#ef4444",
            brightGreen:   "#10b981",
            brightYellow:  "#d97706",
            brightBlue:    "#3b82f6",
            brightMagenta: "#8b5cf6",
            brightCyan:    "#14b8a6",
            brightWhite:   "#451a03",
        },
    },
    lavender: {
        dark: {
            black:         "#18141f",
            red:           "#f87171",
            green:         "#4ade80",
            yellow:        "#fbbf24",
            blue:          "#818cf8",
            magenta:       "#a78bfa",
            cyan:          "#34d399",
            white:         "#ede9fe",
            brightBlack:   "#3b2f5e",
            brightRed:     "#fca5a5",
            brightGreen:   "#86efac",
            brightYellow:  "#fde68a",
            brightBlue:    "#a5b4fc",
            brightMagenta: "#c4b5fd",
            brightCyan:    "#6ee7b7",
            brightWhite:   "#f5f3ff",
        },
        light: {
            black:         "#f5f3ff",
            red:           "#b91c1c",
            green:         "#047857",
            yellow:        "#92400e",
            blue:          "#4338ca",
            magenta:       "#6d28d9",
            cyan:          "#0f766e",
            white:         "#4c1d95",
            brightBlack:   "#ddd6fe",
            brightRed:     "#ef4444",
            brightGreen:   "#10b981",
            brightYellow:  "#d97706",
            brightBlue:    "#6366f1",
            brightMagenta: "#8b5cf6",
            brightCyan:    "#14b8a6",
            brightWhite:   "#2e1065",
        },
    },
    sunset: {
        dark: {
            black:         "#1a1410",
            red:           "#fb7185",
            green:         "#4ade80",
            yellow:        "#fbbf24",
            blue:          "#60a5fa",
            magenta:       "#e879f9",
            cyan:          "#34d399",
            white:         "#ffedd5",
            brightBlack:   "#431407",
            brightRed:     "#fda4af",
            brightGreen:   "#86efac",
            brightYellow:  "#fde68a",
            brightBlue:    "#93c5fd",
            brightMagenta: "#f0abfc",
            brightCyan:    "#6ee7b7",
            brightWhite:   "#fff7ed",
        },
        light: {
            black:         "#fff7ed",
            red:           "#be123c",
            green:         "#047857",
            yellow:        "#b45309",
            blue:          "#1d4ed8",
            magenta:       "#7c3aed",
            cyan:          "#0f766e",
            white:         "#7c2d12",
            brightBlack:   "#fed7aa",
            brightRed:     "#ef4444",
            brightGreen:   "#10b981",
            brightYellow:  "#f59e0b",
            brightBlue:    "#3b82f6",
            brightMagenta: "#8b5cf6",
            brightCyan:    "#14b8a6",
            brightWhite:   "#431407",
        },
    },
    claude: {
        dark: {
            black:         "#1a1917",
            red:           "#e57373",
            green:         "#81c784",
            yellow:        "#ffb74d",
            blue:          "#64b5f6",
            magenta:       "#ce93d8",
            cyan:          "#4db6ac",
            white:         "#f4f3ee",
            brightBlack:   "#4a4540",
            brightRed:     "#d97757",
            brightGreen:   "#a5d6a7",
            brightYellow:  "#ffe0b2",
            brightBlue:    "#90caf9",
            brightMagenta: "#e1bee7",
            brightCyan:    "#80cbc4",
            brightWhite:   "#fdfcfa",
        },
        light: {
            black:         "#faf9f5",
            red:           "#c0392b",
            green:         "#1a7340",
            yellow:        "#8a5c00",
            blue:          "#1565c0",
            magenta:       "#6a1b9a",
            cyan:          "#00695c",
            white:         "#3e2723",
            brightBlack:   "#bcaaa4",
            brightRed:     "#c15f3c",
            brightGreen:   "#388e3c",
            brightYellow:  "#f57f17",
            brightBlue:    "#1976d2",
            brightMagenta: "#7b1fa2",
            brightCyan:    "#00796b",
            brightWhite:   "#141413",
        },
    },
    codex: {
        dark: {
            black:         "#1e1e20",
            red:           "#ef5350",
            green:         "#10a37f",
            yellow:        "#ff9800",
            blue:          "#42a5f5",
            magenta:       "#ab47bc",
            cyan:          "#26c6da",
            white:         "#e0e0e0",
            brightBlack:   "#424242",
            brightRed:     "#ff7043",
            brightGreen:   "#26d198",
            brightYellow:  "#ffb74d",
            brightBlue:    "#64b5f6",
            brightMagenta: "#ce93d8",
            brightCyan:    "#4dd0e1",
            brightWhite:   "#f5f5f5",
        },
        light: {
            black:         "#f5f5f5",
            red:           "#c62828",
            green:         "#00695c",
            yellow:        "#e65100",
            blue:          "#1565c0",
            magenta:       "#6a1b9a",
            cyan:          "#00838f",
            white:         "#212121",
            brightBlack:   "#9e9e9e",
            brightRed:     "#ef5350",
            brightGreen:   "#10a37f",
            brightYellow:  "#ff9800",
            brightBlue:    "#42a5f5",
            brightMagenta: "#ab47bc",
            brightCyan:    "#26c6da",
            brightWhite:   "#111111",
        },
    },
};

const SLOT_TO_CSS: Record<keyof AnsiPalette, string> = {
    black:         "--terminal-ansi-black",
    red:           "--terminal-ansi-red",
    green:         "--terminal-ansi-green",
    yellow:        "--terminal-ansi-yellow",
    blue:          "--terminal-ansi-blue",
    magenta:       "--terminal-ansi-magenta",
    cyan:          "--terminal-ansi-cyan",
    white:         "--terminal-ansi-white",
    brightBlack:   "--terminal-ansi-bright-black",
    brightRed:     "--terminal-ansi-bright-red",
    brightGreen:   "--terminal-ansi-bright-green",
    brightYellow:  "--terminal-ansi-bright-yellow",
    brightBlue:    "--terminal-ansi-bright-blue",
    brightMagenta: "--terminal-ansi-bright-magenta",
    brightCyan:    "--terminal-ansi-bright-cyan",
    brightWhite:   "--terminal-ansi-bright-white",
};

export function applyTerminalPalette(name: ThemeName, isDark: boolean) {
    if (typeof document === "undefined") return;
    const palette = isDark ? PALETTES[name].dark : PALETTES[name].light;
    const style = document.documentElement.style;
    for (const [slot, cssVar] of Object.entries(SLOT_TO_CSS) as [keyof AnsiPalette, string][]) {
        style.setProperty(cssVar, palette[slot]);
    }
}
