import { type ThemePalette } from "./index";

export const vesperTheme: ThemePalette = {
    label: "Vesper",
    light: {
        bgPrimary: "#faf8f5",
        bgSecondary: "#f3f0eb",
        bgTertiary: "#e8e4dc",
        bgElevated: "#fdfcfa",
        textPrimary: "#1a1a1a",
        textSecondary: "#7e7e7e",
        textHeading: "#1a1a1a",
        textHeadingMuted: "#7e7e7e",
        border: "#e0dbd3",
        accent: "#c87830",
        iconMuted: "#7e7e7e",
        shadowSoft: "0 18px 48px rgba(26, 26, 26, 0.08)",
        codeAnchors: {
            comment: "#6e6e6e",
            constant: "#b5530a",
            escape: "#595959",
            function: "#b5530a",
            keyword: "#595959",
            markup: "#b5530a",
            parameter: "#101010",
            property: "#595959",
            string: "#0f7a5e",
            type: "#b5530a",
            typeParameter: "#b5530a",
            variable: "#101010",
        },
    },
    dark: {
        bgPrimary: "#101010",
        bgSecondary: "#0c0c0c",
        bgTertiary: "#1c1c1c",
        bgElevated: "#161616",
        textPrimary: "#ffffff",
        textSecondary: "#a0a0a0",
        textHeading: "#ffffff",
        textHeadingMuted: "#a0a0a0",
        border: "#282828",
        accent: "#ffc799",
        iconMuted: "#909090",
        shadowSoft: "0 24px 56px rgba(0, 0, 0, 0.45)",
        codeAnchors: {
            comment: "#8b8b8b",
            constant: "#ffc799",
            escape: "#a0a0a0",
            function: "#ffc799",
            keyword: "#a0a0a0",
            markup: "#ffc799",
            parameter: "#ffffff",
            property: "#a0a0a0",
            string: "#99ffe4",
            type: "#ffc799",
            typeParameter: "#ffc799",
            variable: "#ffffff",
        },
    },
};
